name: api_grpc_dart
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  get_it: ^7.1.4
  grpc: ^3.0.0
  path: ^1.8.0
  postgres: ^2.3.2
  postgresql2: ^1.0.0
  

dev_dependencies:
  pedantic: ^1.11.1
  dotenv: ^3.0.0