name: api_grpc_dart
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  get_it: ^7.1.4
  grpc: ^3.0.0
  path: ^1.8.0
  postgres: ^2.3.2
  postgresql2: ^1.0.0
  dartz: ^0.10.0-nullsafety.2
  

dev_dependencies:
  dotenv: ^3.0.0
  lints: ^1.0.1
  mockito: ^5.0.10
  test: ^1.17.9
