// Mocks generated by Mockito 5.0.10 from annotations
// in api_grpc_dart/test/data/repository/business_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:api_grpc_dart/data/datasources/list_business_local_data_source.dart'
    as _i2;
import 'package:api_grpc_dart/protos/main.pb.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ListBusinessLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockListBusinessLocalDataSource extends _i1.Mock
    implements _i2.ListBusinessLocalDataSource {
  MockListBusinessLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Business>> listBusiness() =>
      (super.noSuchMethod(Invocation.method(#listBusiness, []),
              returnValue: Future<List<_i4.Business>>.value(<_i4.Business>[]))
          as _i3.Future<List<_i4.Business>>);
}
