// Mocks generated by Mockito 5.0.10 from annotations
// in api_grpc_dart/test/data/repositories/business_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:api_grpc_dart/data/datasources/business_local_data_source.dart'
    as _i2;
import 'package:api_grpc_dart/protos/protos/main.pb.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [BusinessLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBusinessLocalDataSource extends _i1.Mock
    implements _i2.BusinessLocalDataSource {
  MockBusinessLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Business>> listBusiness(
          {_i4.LatLng? latLng, List<String>? notIds}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #listBusiness, [], {#latLng: latLng, #notIds: notIds}),
              returnValue: Future<List<_i4.Business>>.value(<_i4.Business>[]))
          as _i3.Future<List<_i4.Business>>);
}
