// Mocks generated by Mockito 5.0.15 from annotations
// in api_grpc_dart/test/data/repositories/item_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:api_grpc_dart/data/datasources/item_local_data_source.dart'
    as _i3;
import 'package:api_grpc_dart/protos/protos/main.pb.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:postgres/postgres.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeSearchItemResponse_0 extends _i1.Fake
    implements _i2.SearchItemResponse {}

/// A class which mocks [ItemLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemLocalDataSource extends _i1.Mock
    implements _i3.ItemLocalDataSource {
  MockItemLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Item>> listItem(
          {_i5.PostgreSQLExecutionContext? context,
          Map<String, dynamic>? data,
          List<String>? paths}) =>
      (super.noSuchMethod(
              Invocation.method(#listItem, [],
                  {#context: context, #data: data, #paths: paths}),
              returnValue: Future<List<_i2.Item>>.value(<_i2.Item>[]))
          as _i4.Future<List<_i2.Item>>);
  @override
  _i4.Future<_i2.SearchItemResponse> searchItem(
          {_i5.PostgreSQLExecutionContext? context,
          Map<String, dynamic>? data,
          List<String>? paths}) =>
      (super.noSuchMethod(
          Invocation.method(
              #searchItem, [], {#context: context, #data: data, #paths: paths}),
          returnValue: Future<_i2.SearchItemResponse>.value(
              _FakeSearchItemResponse_0())) as _i4
          .Future<_i2.SearchItemResponse>);
  @override
  _i4.Future<_i2.Item?> getItem(
          {_i5.PostgreSQLExecutionContext? context,
          Map<String, dynamic>? data,
          List<String>? paths}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getItem, [], {#context: context, #data: data, #paths: paths}),
          returnValue: Future<_i2.Item?>.value()) as _i4.Future<_i2.Item?>);
  @override
  String toString() => super.toString();
}
