// Mocks generated by Mockito 5.0.15 from annotations
// in api_grpc_dart/test/data/repositories/object_storage_repository_impl_test.dart.
// Do not manually edit this file.

// Dart imports:
import 'dart:async' as _i3;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

import 'package:api_grpc_dart/data/datasources/object_storage_data_source.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ObjectStorageDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectStorageDataSource extends _i1.Mock
    implements _i2.ObjectStorageDataSource {
  MockObjectStorageDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> presignedPutObject(String? bucket, String? object,
          {int? expires}) =>
      (super.noSuchMethod(
          Invocation.method(
              #presignedPutObject, [bucket, object], {#expires: expires}),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  String toString() => super.toString();
}
