// Mocks generated by Mockito 5.0.15 from annotations
// in api_grpc_dart/test/data/repositories/verification_code_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:api_grpc_dart/data/datasources/verification_code_local_data_source.dart'
    as _i3;
import 'package:api_grpc_dart/protos/protos/main.pb.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeVerificationCode_0 extends _i1.Fake implements _i2.VerificationCode {
}

/// A class which mocks [VerificationCodeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerificationCodeLocalDataSource extends _i1.Mock
    implements _i3.VerificationCodeLocalDataSource {
  MockVerificationCodeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.VerificationCode> createVerificationCode(
          {Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
              Invocation.method(#createVerificationCode, [], {#data: data}),
              returnValue:
                  Future<_i2.VerificationCode>.value(_FakeVerificationCode_0()))
          as _i4.Future<_i2.VerificationCode>);
  @override
  _i4.Future<List<_i2.VerificationCode>> listVerificationCode() =>
      (super.noSuchMethod(Invocation.method(#listVerificationCode, []),
              returnValue: Future<List<_i2.VerificationCode>>.value(
                  <_i2.VerificationCode>[]))
          as _i4.Future<List<_i2.VerificationCode>>);
  @override
  _i4.Future<_i2.VerificationCode> getVerificationCode({String? id}) => (super
          .noSuchMethod(Invocation.method(#getVerificationCode, [], {#id: id}),
              returnValue:
                  Future<_i2.VerificationCode>.value(_FakeVerificationCode_0()))
      as _i4.Future<_i2.VerificationCode>);
  @override
  void deleteVerificationCode({String? id}) => super.noSuchMethod(
      Invocation.method(#deleteVerificationCode, [], {#id: id}),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
