// Mocks generated by Mockito 5.0.10 from annotations
// in api_grpc_dart/test/data/repositories/verification_code_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:api_grpc_dart/core/error/failure.dart' as _i5;
import 'package:api_grpc_dart/data/datasources/verification_code_local_data_source.dart'
    as _i3;
import 'package:api_grpc_dart/protos/protos/main.pb.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [VerificationCodeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerificationCodeLocalDataSource extends _i1.Mock
    implements _i3.VerificationCodeLocalDataSource {
  MockVerificationCodeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.VerificationCode>>
      createVerificationCode({Map<String, dynamic>? data}) =>
          (super.noSuchMethod(
              Invocation.method(#createVerificationCode, [], {#data: data}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.VerificationCode>>.value(
                      _FakeEither<_i5.Failure, _i6.VerificationCode>())) as _i4
              .Future<_i2.Either<_i5.Failure, _i6.VerificationCode>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, Iterable<_i6.VerificationCode>>>
      listVerificationCode() => (super.noSuchMethod(
          Invocation.method(#listVerificationCode, []),
          returnValue: Future<
                  _i2.Either<_i5.Failure, Iterable<_i6.VerificationCode>>>.value(
              _FakeEither<_i5.Failure, Iterable<_i6.VerificationCode>>())) as _i4
          .Future<_i2.Either<_i5.Failure, Iterable<_i6.VerificationCode>>>);
}
