name: postgres_dao
description: A Postgres Dao.
version: 0.0.1
# homepage: https://www.example.com

publish_to: 'none'

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  path: ^1.8.0
  postgres: ^2.3.2

dev_dependencies:
  # dart run build_runner build
  build_runner: ^2.0.5
  lints: ^1.0.1
  mockito: ^5.0.10
  test: ^1.17.9
